### ISSUE TITLE
[feature-request] Specify disks to monitor

### ISSUE THREAD

**Issue by ionlights** [xxxserxxx/gotop#126]
Unsure if this would be feasible; but, I have a few dozen partitions (lvms and zfs datasets). `gotop` pulls in all of those partitions, however, I don't necessarily need to see all of them.

Would it be feasible to filter the partitions being monitored? e.g. filtering by either permissions or by a custom regex.

**Comment by xxxserxxx** [comment]
@ionlights Yes!  Please track #108 . Filtering was implemented on the v4.0 branch on thermal sensors to support OSX, which reports *waaaay* too many thermometers, and there are plans to extend this to other metrics.  I'm a *little* concerned because this does add overhead for every refresh; I'm worried about the performance impact of having filtering on everything, but it'll probably go in anyway and I'll figure out how to optimize it somehow.

If #108 looks like it'd cover your request, could you close this one?
