### ISSUE TITLE
Lines glitch in Konsole terminal

### ISSUE THREAD

**Issue by cyruzin** [xxxserxxx/gotop#129]
I'm using Arch Linux with LTS kernel and KDE, the terminal is Konsole. How can I fix this?

![81960812-e3cbf500-95e7-11ea-98ac-f188e40af7e7](https://user-images.githubusercontent.com/2396581/82101035-b2cfeb00-96e1-11ea-9be9-a403fcdd061d.png)

**Comment by xxxserxxx** [comment]
@cyruzin thanks for reposting this.  This is a font issue; those two graphs need braille code points for rendering, and sometimes encoding.  Can you please ensure that you have ttf-ubraille installed (`pacman -S ttf-ubraille`) and that your terminal encoding is set to UTF-8? This last may be a terminal GUI setting -- I'm not familiar with Konsole -- but you can also check what $LANG is set to (`printenv | grep LC` or `echo $LANG`).  For me, for example, since my native language is English my LANG is set to `en_US.UTF-8` -- yours should be set to your language + `.UTF-8`.

**Comment by cyruzin** [comment]
Yes, I have "ttf-ubraille" font installed, from AUR. My lang is "en_US.UTF-8". Konsole encoding is UTF-8. Perharps I need to install something more or setup some setting in Konsole.

**Comment by cyruzin** [comment]
Look what I found: https://www.reddit.com/r/archlinux/comments/apqnhr/ugly_graph_in_gotop/

**Comment by cyruzin** [comment]
@xxxserxxx changing the Konsole font fix the issue. 

![image](https://user-images.githubusercontent.com/2396581/82108258-ae1c2e80-9703-11ea-998f-10da908521e1.png)

**Comment by xxxserxxx** [comment]
Hooray!  Glad you found a solution.
