### ISSUE TITLE
[Question]How to select htop-like layout in gotop 4.1.3?

### ISSUE THREAD

**Issue by quaggalinux** [xxxserxxx/gotop#211]
Hi,

Gotop 4.1.3 release notes said it can select htop-like layout. But I cannot select it in command line.

I used gotop_v4.1.3_linux_amd64.tgz to unpack. I only see a gotop file and there are not an extra layout file.

Thank you!

**Comment by xxxserxxx** [comment]
How did you install gotop?  Have you tried `gotop -l htop`?

It doesn't show up in `gotop --list layouts` because those only include the compiled-in layouts; htop gets installed into `/etc/gotop` by the packages. If you compiled gotop yourself, you need to do one of the following:

1. Copy the file [`gotop/layouts/htop`](https://github.com/xxxserxxx/gotop/blob/master/layouts/htop) into `~/.config/gotop`
2. Copy that file into wherever you run gotop from
3. Run `gotop -l` with the full path to the htop directory.

For example, if you cloned gotop into `${HOME}/gotop` you *could* run `gotop -l ${HOME}/gotop/layouts/htop`.  It's easier to just create `~/.config/gotop` and copy the `htop` file there, though; `gotop -l htop` will find it if it's there. Same with any other layout.
