### ISSUE TITLE
[feature-request] MacOS builds

### ISSUE THREAD

**Issue by ionlights** [xxxserxxx/gotop#60]
I'm not sure what @cjbassi's process for doing MacOS builds were, but I think that would be exceptionally helpful to have – as I personally have an Arch Linux server, but also use MacOS quite frequently.

Is there any help you need with submitting releases to `brew`? I know that @cjbassi used a separate `tap`, which I believe just means that `brew` clones the repo and builds from source.

https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

I believe I could take a crack at this and supply a PR for it, if that would be helpful?

**Comment by xxxserxxx** [comment]
I'm not building for Darwin; it took a bit because of the CGO requirements, but it'll be great if you can test the builds and verify that they work.  I'll provide a binary in the beta.

As far as the `tap`, I didn't see sources for it in the repository; I'll take all the help I can get with this.

**Comment by ionlights** [comment]
Ahh, I see how cjbassi's doing things: https://github.com/cjbassi/homebrew-gotop/blob/master/gotop.rb

**Comment by ionlights** [comment]
Just to be clear – this is the process to build across all platforms, yes? https://github.com/xxxserxxx/gotop#building

The main reason there aren't MacOS builds is because you just don't have MacOS, from what I understand.

**Comment by xxxserxxx** [comment]
Thanks; I really appreciate it.  Assigned to you.

A couple of questions:

- Is gotop currently being tapped from cjbassi's source, or is it part of the homebrew stdlib?
- What's the process for updating the homebrew master source?  Who do we have to talk to?
- Do github actions provide for compiling on different platforms, e.g. Darwin?

If we have to keep it as a tap, we can either put it in here or tap it from your's; I don't care, as long as people know how to get to it.

I've been using a script in the repository (make.sh) to create the binaries, then I just do everything else manually.  I'm not particularly familiar with git; I'm really only using it for this project.  If we can automate builds, that'd be awesome.  I looked at goreleaser earlier, but something got me stuck and it wasn't a priority.

Because the OSX build requires cross-compiling, *and* because it requires Darwin headers, I'm using the dockercore/golang-cross Docker project to build the binaries.

OpenBSD is also an issue currently because it also requires special headers and I haven't found a cross-compiler docker for that.

P.S., you responded before I finished writing this: yes, that's correct.  `go get` should work on Linux -- as yet, there is no CGO required for Linux (although that'll change with the GPU support, which I'm not looking forward to).

Also, there *are* OSX builds; I pushed out [v3.3.2](https://github.com/xxxserxxx/gotop/releases/tag/v3.3.2) yesterday and included Darwin builds.  I have no idea if they work or not.

**Comment by xxxserxxx** [comment]
Ok: https://github.com/xxxserxxx/homebrew-gotop

Updated for v3.3.2

**Comment by ionlights** [comment]
> * Is gotop currently being tapped from cjbassi's source, or is it part of the homebrew stdlib?

`gotop` on MacOS is tapped from cjbassi's source. **Aside:** `taps` on Homebrew aren't part of `homebrew`'s stdlib. In the long-haul, it might make sense to allow something like `gotop` in there (as I've seen plenty of other CLI tools packaged up), but I'm not sure how to go about that just yet.

> * What's the process for updating the homebrew master source?  Who do we have to talk to?

Broadly, I'm not sure. Additionally, does this allude to what I mentioned on the prior quote?

> * Do github actions provide for compiling on different platforms, e.g. Darwin?

Briefly, yes. Though only for MacOS Catalina (10.15). I discuss it a wee more in #63.

> Because the OSX build requires **cross-compiling**, _and_ because it requires Darwin headers, I'm using the dockercore/golang-cross Docker project to build the binaries.

What do you mean by cross-compiling? 

> ... as yet, there is no CGO required for Linux (although that'll change with the GPU support, which I'm not looking forward to).

I think, once you have that sorted, this may make sense as an additional package? Might get a little hairy with supporting MacOS and GPUs since they're iGPUs or AMD, and iirc AMD wasn't planned as initial support.

**Comment by xxxserxxx** [comment]
> it might make sense to allow something like gotop in there (as I've seen plenty of other CLI tools packaged up), but I'm not sure how to go about that just yet.

Hm.  Ok, we leave out homebrew+stdlib for now.  I have no problem with using your tap; I'm happy to have instructions in the README pointing to it.

> What do you mean by cross-compiling?

I am building Darwin binaries and uploading those in the releases since v3.3.2.  To get those, I have to cross-compile.  I'd prefer the brew pull binaries than force everybody to have Go installed to compile it -- can we do it that way?  I do need someone to sanity check the OSX builds I'm creating, though.

> I think, once you have that sorted, this may make sense as an additional package?

Excellent; this echos something I've been considering: using Go's plug-in capability for some of these features.  I've been working on abstracting devices so they're not so coupled with the widgets; once this is done, they could be provided as plugins.  It'd allow the core package to remain lean(er) for stuff like virtual-devices-over network, and uncommon (as in, not everybody has them) devices like specific GPUs, or external specialty-purpose devices like weather stations.  

I've been a little uncomfortable taking gotop into the remote-monitoring space because of feature creep and bulk, and plugins might address that nicely.

**Comment by ionlights** [comment]
> I am building Darwin binaries and uploading those in the releases since v3.3.2. To get those, I have to cross-compile. I'd prefer the brew pull binaries than force everybody to have Go installed to compile it -- can we do it that way? I do need someone to sanity check the OSX builds I'm creating, though.

Brew/Taps will pull binaries, yes.

**Comment by ionlights** [comment]
Do you have a target date for 3.4.0 release? Will help me schedule things personally – I have a significant number of deadlines in the next 2.5wks of so. 😕

**Comment by xxxserxxx** [comment]
I do not. I'm planning on releasing when it's ready to support GPUs in general, and NVIDIA in particular, and that's going to take some more time.  I've essentially decided to use plugins for these sorts of devices, which removes the need for big-bang top-level package changes, but NVIDIA is the big target for v3.4.0; it has the most noisy user base.

**Comment by ionlights** [comment]
So, in #63 you mentioned MacOS builds – do you still need my help on this? Most of it involved just creating the Tap repository (which you already did), and then making sure version bumps and SHAs get propagated to that Tap repository from here.

From what it sounds like, only that last bit is remaining for the automated builds to work nicely with `brew`?

**Comment by xxxserxxx** [comment]
Yes, I would like help testing the Darwin builds.

I've pushed Homebrew instructions to the Readme -- are you able to test the instructions?  It pulls a binary I created manually, but with the same process as the Github workflow, so if the v3.3.2 recipe works then the 3.4.x (or, as it may turn out, 3.5.0 by the time I release it) should work as well.  I'd really like feedback about whether gotop behaves on Darwin, and especially whether the binaries run.  In addition to basic behavior and whether the instrumentation works, I'm concerned about whether the braille fonts are rendered properly, and how the CPU use of the app works.

I think everything is done.  I have automated builds working using Actions, and pre-releases are being created, so all that I'll need to do is tag, edit the change log, and publish.  

Actually, now that I think about it, a workflow that gets triggered on a successful build is needed to update the tap; something similar is needed for the AUR repos.  I guess I'll work on that next while I wait for feedback from testers.

If you're able to test the Darwin tap (and resulting executable), that'd be a huge help.

**Comment by xxxserxxx** [comment]
The tap is live; the README has been updated.  The tap still needs to be tested, but this ticket is addressed.  If there are issues with the tap, we should have new tickets for those.

**Comment by xxxserxxx** [comment]
Caleb's gotop is in homebrew/core, and that'll always get pulled first. I'll update the instructions in the README until we can get Homebrew to change the stdlib recipe.

**Comment by ionlights** [comment]
Yea, I just saw this as I was testing. 😕 I'm looking into how to change the recipe in `homebrew-core`.

**Comment by ionlights** [comment]
![image](https://user-images.githubusercontent.com/5000729/75710979-95b77e80-5c93-11ea-857c-4575efe6f623.png)

Based on what I'm seeing in cjbassi's formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/gotop.rb) – it looks like he's having `brew` build locally.

**Comment by xxxserxxx** [comment]
Ok.  The workflow should update the tag and push it, but I won't be able to test that until the next release.

**Comment by ionlights** [comment]
Alright, I'll see what more I can gather about doing the migration – unsure if Homebrew's a similar community to AUR, where it needs the maintainer to confirm transfer.
