### ISSUE TITLE
kitchensink layout is not bundled correctly.

### ISSUE THREAD

**Issue by SuperSandro2000** [xxxserxxx/gotop#72]
##### gotop version:
```
$ git rev-parse HEAD
be42ba538cefc892d1dc3d18c783483f4875baff
```
##### OS/Arch:
```
$ uname -or
5.4.0-4-amd64 GNU/Linux
```
##### Terminal emulator: 
Konsole

##### Any relevant hardware info:
If the issue is clearly related to a specific piece of hardware, e.g., the network
##### tmux version:
`tmux -V`, if using tmux

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

```
$ cat ~/.local/state/gotop/errors.log
21:39:29 main.go:459: Unable to open layout file /home/sandro/.config/gotop/kitchensink or ./kitchensink
```

Edit:
Executing it with the relative path does work `./gotop -l layouts/kitchensink`.

Actions:

1. [X] I modified the `-h` text and added kitchensink, but didn't actually embed the layout. 6150c58
2. [X] The aur (and homebrew) packages don't (yet) copy the layouts into directories `gotop` can find them. Created #74 to track this.
3. [X] Not all layouts that I add to the repo are going to be bundled into the executable. People compiling by hand or used `go get` need to manually copy layouts into `$XDG_CONFIG_DIR/gotop` directory. The `README` should also mention this, and also point people to the`$GOPATH/src/github.com/xxxserxxx/gotop/layouts/` directory.  Created #75 to track this.

**Comment by xxxserxxx** [comment]
There are four issues here; I'll leave this ticket open until all three are resolved.

1. I modified the `-h` text and added kitchensink, but didn't actually embed the layout.
2. The aur (and homebrew) packages don't (yet) copy the layouts into directories `gotop` can find them
3. Not all layouts that I add to the repo are going to be bundled into the executable. People compiling by hand or used `go get` need to manually copy layouts into `$XDG_CONFIG_DIR/gotop` directory. The `README` should also mention this, and also point people to the`$GOPATH/src/github.com/xxxserxxx/gotop/layouts/` directory.

**Comment by SuperSandro2000** [comment]
About 2: Can you add a debian package?
About 3: There is no way to copy that? That is probably a step many people miss.
Also my $GOPATH is in my $HOME so how can I copy the layout for all users?

**Comment by xxxserxxx** [comment]
Yes. I've been working to get the releases automated, and debs and rpms (and everything else) still needs to be added, as well as adding system-wide installation of things like color schemes.  The current code doesn't support system-wide configurations; it wasn't something supported by the code base when I took over project mantainership, and I'm just adding it now.

There's no standard way of copying files into the right directories.  `go install` and `go get` don't provide a mechanism.  If people aren't going to read instructions on copying files, I doubt they'll read instructions on additional programs they need to run to copy files around.  And there's no point in building it into the executable, because it doesn't know where the source files are.

At some point, I may add an extension to download contributed color schemes and layouts from a git repository, but that's a ways out.  For now, you'll have to put any layouts or color schemes that aren't built-in into `~/.config/gotop`.

**Comment by xxxserxxx** [comment]
Tickets created for the steps so they can be more easily tracked.
