### ISSUE TITLE
[Feature request] Disable error logging by default

### ISSUE THREAD

**Issue by whooperr** [xxxserxxx/gotop#86]
Would it be possible to disable logging by default? The error.log is quite write intensive (a few writes per second) and has, in my opinion, little value to the end user.
 What do you think?

**Comment by xxxserxxx** [comment]
@whooperr ,

I left in debugging in the last version, and that may be the one you have.  The logs should **only** include errors.  The next minor update removes this -- it slipped in, and correcting a bad release by "fixing" binaries without issuing a new release turns out to me a massive PITA because of cascading changes to the downstream distribution channels (AUR, homebrew, Nix, etc).  Long story short, I'm sorry about that, and if you can wait for v3.5.1 this should be resolved.

Are you in a position to compile from source and see if this reduces the logging?  If so, please do and if the logs get quiet, please let me know by closing this.  Otherwise, if you believe you're seeing spurious, non-error message in the log, please attach the log here and let me see what's being chatty -- I will either resolve it, or consider disabling the logs.

**Comment by xxxserxxx** [comment]
No response; closing as the log message in question (as described by #85) was fixed in trunk and will be addressed in the next release.  Only true errors should be reported, and these I'd like to hear about.
