### ISSUE TITLE
colors for memory and swap are inverted

### ISSUE THREAD

**Issue by deathtrip** [xxxserxxx/gotop#91]
##### gotop version:
3.5.1
##### OS/Arch:
Arch Linux
##### Terminal emulator: 
Terminator

Sometimes when starting gotop, the colors for main memory and swap are inverted. Restarting gotop (sometimes twice) brings it back to normal. I use the default color scheme.

**Comment by xxxserxxx** [comment]
Hm.  I'll have to look into this; I think colors are assigned in the order that memory is returned from the library, so there's an element to randomness.  I'll see if there's something I can do about that, at least for main memory.

**Comment by xxxserxxx** [comment]
Yup.  Sure enough, battery and CPU had code to ensure consistent color assignment, but this was missing on memory.  This was, incidentally, my fault since, in the inherited code, the memory data was static; with the abstraction of devices, memory became dynamic and I missed the key sort.

This will be in the 3.6 release.
